package com.bank.credit.model;

import com.bank.credit.model.enums.CreditType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a credit product entity stored in MongoDB.
 * Supports personal credits, business credits, and credit cards.
 *
 * <p>Business rules:</p>
 * <ul>
 *   <li>PERSONAL_CREDIT: max 1 per personal customer</li>
 *   <li>BUSINESS_CREDIT: unlimited per business customer</li>
 *   <li>CREDIT_CARD: unlimited for both customer types</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "credits")
public class Credit {

    /** Unique identifier generated by MongoDB. */
    @Id
    private String id;

    /** Unique credit number assigned at creation. */
    @Indexed(unique = true)
    private String creditNumber;

    /** Type of credit product. */
    private CreditType creditType;

    /** ID of the customer who owns this credit (from ms-customer). */
    private String customerId;

    /**
     * Total approved credit limit.
     * For credit cards: the spending limit.
     * For loans: the total loan amount.
     */
    private BigDecimal creditLimit;

    /**
     * Outstanding balance owed by the customer.
     * For credit cards: amount spent not yet paid.
     * For loans: remaining balance to be paid.
     */
    @Builder.Default
    private BigDecimal outstandingBalance = BigDecimal.ZERO;

    /**
     * Available balance for credit cards only.
     * Calculated as: creditLimit - outstandingBalance.
     */
    @Builder.Default
    private BigDecimal availableBalance = BigDecimal.ZERO;

    /**
     * Indicates if the credit has an overdue payment.
     * Used in Part III to block new product acquisition.
     */
    @Builder.Default
    private Boolean isOverdue = false;

    /** Due date for loan payments or credit card billing cycle. */
    private LocalDateTime dueDate;

    /** Indicates if the credit product is currently active. */
    @Builder.Default
    private Boolean status = true;

    /** Timestamp when the credit was created. */
    @CreatedDate
    private LocalDateTime createdAt;

    /** Timestamp when the credit was last updated. */
    @LastModifiedDate
    private LocalDateTime updatedAt;
}